<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class Event extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug', 'details'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($item){

//            Log::info('Creting Event:', $item);

            $item->slug = Str::slug($item->name);
        });

        static::created(function($item) {

//            Log::info('Created Event: ', $item);

        });

        static::updating(function ($item) {

//            Log::info('Updating Event:', $item);

            $item->slug = Str::slug($item->slug);
        });

        static::updated(function ($item) {

//            Log::info('Updating Event:', $item);

        });

        static::deleted(function ($item) {

//            Log::info('Deleted Event', $item);

        });
    }
}
